
# Site settings
title: 打个大西瓜
SEOTitle: 打个大西瓜 | BLOG
header-img: img/post-bg-desk.jpg
email: fengzhouxuan@qq.com
description: "醉后不知天在水，满船清梦压星河"
keyword: "打个大西瓜 Blog"
url: "https://fengzhouxuan.github.io/"          # your host, for absolute URL
baseurl: ""
#baseurl: "/bom" # the subpath of your site, e.g. /blog      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/fengzhouxuan/fengzhouxuan.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Too Old To Be Yourself"
sidebar-avatar: /img/longmao.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

#Page
#分页显示 jekyll 3.0中声明方式
plugins: [jekyll-paginate]
#分页 2.0
gems: [jekyll-paginate]
paginate: 5
# paginate_path: "page:num"

# SNS settings
RSS: false
# weibo_username:     ckjcode
# zhihu_username:     ckjcode
github_username:    fengzhouxuan
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
#twitter_username:   ckjcode




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: ckjcode

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 6e0e0132e43fc499efc7                            #生成的clientID
  clientSecret: 1ab3c044680aa975253bd1d4ab9c9f2ae299c343    #生成的clientSecret
  repo: fengzhouxuan.github.io    #仓库名称
  owner: fengzhouxuan    #github用户名
  admin: fengzhouxuan
  distractionFreeMode: false #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: ckjcode.gitee.io               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



 #Friends
friends: [
    {
        title: "长胖是个梦想",
        href: "https://zhoujun2303.github.io/"
    },
]
